[phases.setup]
nixPkgs = ["nodejs_20"]
cmds = ["corepack enable"]

[phases.install]
cmds = ["cd ../.. && pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["cd ../.. && pnpm --filter client build"]

[start]
cmd = "npx serve dist -s -l $PORT"
